url: https://lailson.github.com
baseurl: /poscead

# Site settings
title: POSCEAD
email: lailson.pi@gmail.com
description: "Site para disciplina de Cibercultura e Inteligência coletiva - Posgraduação."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Kalyana
  pic: 1
  position: Formação
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Lailson Henrique
  pic: 2
  position: Professor com Pós-graduação em Redes de Computadores, Desenvolvedor Web
  social:
    - title: twitter
      url: # https://twitter.com/lailsonh
    - title: facebook
      url: # https://www.facebook.com/lailson.henrique
    - title: linkedin
      url: # 

- name: Francisca Dark
  pic: 3
  position: Professora
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty